### ISSUE TITLE
Mouse wheel scrolling

### ISSUE THREAD

**Issue by MarkusPint** [appknox/droid-VNC-server#10]
Hi,

Looks like mouse wheel scrolling events are not acted upon on the device. Other mouse events work, though.

Scrolling is only possible by "dragging", which is pretty cumbersome.

Any thoughts?

**Comment by subho007** [comment]
Sorry, for now dragging is the only way to move forward, since scrolling in an app can happen in any arbitrary direction.

**Comment by mixaz** [comment]
I fixed it in my fork: https://github.com/mixaz/droid-VNC-server/commit/a821af70332c9a81e80728e6e27eda1b0df3d50d
